feature: ['feature/*', 'feat/*']
fix: ['fix/*', 'hotfix/*']
ci: ['ci/*']
refactor: ['refactor/*']
style: ['style/*']
docs: ['docs/*', 'doc/*']
test: ['test/*']
chore: ['chore/*']
performance: ['performance/*', 'perf/*', 'infrastructure/*', 'infra/*']
